[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[[bin]]
name = "day1"
path = "./src/day1.rs"

[[bin]]
name = "day2"
path = "./src/day2.rs"

[dependencies]
